googleAnalytics = "G-946N9V2H6F"


baseurl = "http://www.zihengjackchen.com"
title = "Home"
theme = ["hugo-video", "hugo-coder"]
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
  style = "github-dark"

[params]
  author = "Ziheng (Jack) Chen"
  info = "MS Student in Computer Engineering @ UIUC"
  
  description = "Jack's personal website"
  keywords = "Ziheng Chen, Chen Ziheng, Jack Chen, UIUC, 陈自衡"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "images/green_check.png"
  favicon_16 = "images/green_check.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["main.css"]
  # customSCSS = ["main.scss"]
  # customJS = ["js/custom.js"]


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/zihengjackchen"

[[params.social]]
  name = "Gitlab"
  icon = "fa fa-2x fa-gitlab"
  weight = 2
  url = "https://gitlab.com/zihengjackchen"

  
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/zihengjackchen/"

[[params.social]]
  name = "Email"
  icon = "fa fa-2x fa-envelope"
  weight = 4
  url = "mailto:zihengchen2000@gmail.com"


[languages.en]
  languageName = ":us:"

[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url = "about/"

  
[[languages.en.menu.main]]
  name = "Experience"
  weight = 2
  url = "experience/"

[[languages.en.menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"

[[languages.en.menu.main]]
  name = "Skills"
  weight = 4
  url = "skills/"

[[languages.en.menu.main]]
  name = "Education"
  weight = 5
  url = "education/"
